### ISSUE TITLE
Add support for rendering ClinicalDocument/sdtc:statusCode when included in a document.

### ISSUE THREAD

**Issue by LisaRNelson** [HL7/CDA-core-xsl#21]
When Creating Patient Authored Advance Directive Documents, we have come across a need to represent a document that has been “voided” by the Patient.  
E.g. Person creates a TX Living Will form while living in TX.  Five years later the person moves to MI and creates a new MI Advance Directive Document. The person explicitly voids the TX Living Will because it is no longer relevant.  The document was not “entered in error”, it was correctly in place for 5 years.  We do want a new version of the document to be registered with the “voided” status so that organizations that have previously retrieved that document will now get the “current version” which will show that this document has been “voided”.  
[Stylesheet Change Request.pptx](https://github.com/HL7/CDA-core-xsl/files/12587660/Stylesheet.Change.Request.pptx)

To address this need we are adding a constraint to use the ClinicalDocument/sdtc:statusCode field.  Thus, we are requesting that the stylesheet render this extension when it is included in a document.

**Comment by ahenket** [comment]
I had already opened ticket #18 for this. Please refer to that ticket for further updates
